setwd('/lustre/project/og04/shichunwei/project/bisulfite_sequencing/script')
data<-read.table('07.out')
col<-as.matrix(data[2])
name<-as.matrix(data[1])
png('07.png')
counts<-as.matrix(data[3:5])
par(las=1)
barplot(counts,width=0.05,ylim=c(0,100),col=col,ylab="Percentage (%)",names.arg=c('sample1','sample2',NA))
legend('right',name,bty='o',pch=c(15),col=col,cex=2)
dev.off()
